[project]
name = "calculator"
version = "0.1.0"
description = "This an assignment about making a calculator app"
readme = "README.md"
authors = [
    { name = "Nikolai Sandbeck", email = "sandbeck1990@protonmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mypy>=2.3.1",
    "typing>=3.10.0.0",
]

[project.scripts]
calculator = "calculator:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pylint>=4.0.8",
]

[tool.mypy]
strict = true
plugins = []
